- name: Configure Docker on Elk VM
  hosts: elk
  remote_user: azureuser
  become: true
  tasks:    
  - name: Install Docker
    apt:
      force_apt_get: yes
      name: docker.io
      state: present    
  - name: Install python3-pip
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present    
  - name: Install Docker Modules
    pip:
      name: docker
      state: present    
  - name: Increase Memory
    command: sysctl -w vm.max_map_count=262144    
  - name: Use More Mem
    sysctl:
      name: vm.max_map_count
      value: '262144'
      sysctl_file: /etc/sysctl.conf
      state: present    
  - name: Launch Elk Container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
       - 5601:5601
       - 9200:9200
       - 5044:5044